database:
  host: localhost
  port: 3306
  username: root
  password: root
  name: bungeecord

teamspeak:
  host: localhost
  port: 9987
  username: admin
  password: admin
  nickname: Bot

debug: false